name: List Tags For Release
run-name: List Tags For release for tag ${{ github.event_name }} by @${{ github.actor }}

on:
  pull_request:
    types:
      - opened
    branches:
      - 'release**'
      - 'Release**'
      - 'master'
jobs:
    display_ops_PRs:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: "Build Changelog"
          id: build_changelog
          uses: tiwanari/list-merged-pull-requests@master
          with:
            token: ${{ github.token }}
            
        - name: "Edit Release PR"
          id: edit_release_pr
          uses:  nefrob/pr-description@v1.2.0
          with:
            content: "Ops Changes: \n ${{steps.build_changelog.outputs}}"
            token: ${{ secrets.GITHUB_TOKEN }}