name: List Tags For Release
run-name: List Tags For release for tag ${{ github.event_name }} by @${{ github.actor }}

on:
  pull_request:
    types:
      - opened
    branches:
      - 'release**'
      - 'Release**'
      - 'master'
jobs:
    display_ops_PRs:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Bump version and push tag
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            tag_prefix: "pre-"
          
        - name: "Build Changelog"
          id: build_changelog
          uses: mikepenz/release-changelog-builder-action@v5.0.0
          with:
            configurationJson: |
              {
                "categories": [
                {
                  "title": "## Ops changes:",
                  "labels": ['ops:**'']
                }
                ],
                "ignore_labels": [
                  "ignore"
                ],
                "sort": {
                  "order": "ASC",
                  "on_property": "mergedAt"
                },
                "template": "#{{CHANGELOG}}\n\n<details>\n</details>",
                "pr_template": "- ##{{NUMBER}} - #{{TITLE}} #{{LABELS}}\n",
                "empty_template": "- no ops changes",
                "label_extractor": [
                  {
                    "pattern": "(.) (.+)",
                    "target": "$1",
                    "flags": "gu"
                  },
                  {
                    "pattern": "\\[Issue\\]",
                    "on_property": "title",
                    "method": "match"
                  }
                ],
                "duplicate_filter": {
                  "pattern": "\\[ABC-....\\]",
                  "on_property": "title",
                  "method": "match"
                },
                "reference": {
                  "pattern": ".*\\ \\#(.).*",
                  "on_property": "body",
                  "method": "replace",
                  "target": "$1"
                },
                "transformers": [
                  {
                    "pattern": "[\\-\\*] (\\[(...|TEST|CI|SKIP)\\])( )?(.+?)\n(.+?[\\-\\*] )(.+)",
                    "target": "- $4\n  - $6"
                  }
                ]
              }
        - name: "Edit Release PR"
          id: edit_release_pr
          uses:  nefrob/pr-description@v1.2.0
          with:
            content: "Ops Changes: \n ${{steps.build_changelog.outputs.changelog}}"
            token: ${{ secrets.GITHUB_TOKEN }}